### ISSUE TITLE
Fix token prices that does not work properly

### ISSUE THREAD

**Issue by AnthonyAkentiev** [ETHLend/DAPP#33]
There are some tokens that get ZERO price from coinmarketcap...
Check here - https://app.ethlend.io

List of tokens: 

ETHLend --> also change the name to LEND
MKR Maker
TrustCoin We Trust
FirstBlood
TaasFund
Distric0x
Numeraire
Xaurum
Humaniq
TokenCard
Guppy - MatchPool
Time ChronoBank
AdToken
SwarmCity
Etheroll
NimiqNetwork
Lunyr
Bcap - Blockchain Capital
Pluton - Plutus.it
Vslice

**Comment by AnthonyAkentiev** [comment]
@enkogu These tokens do not work((((

FirstBlood
Xaurum
Guppy
Matchpool
Etheroll
Vslice

**Comment by enkogu** [comment]
Now all manually checked
